language: ruby

sudo: false

cache: bundler

deploy:
  provider: script
  script: scripts/post-advisories.sh
  on:
    branch: master

notifications:
  irc: chat.freenode.net#rubysec

env:
  global:
  - secure: A5bSzdAibDt6Go6gFXt/L07Ip0BGIt8hK6fixTF5kgqAUQBMV/ZlF5DbaOdV6yu309tRaemVicxqX0SgatPHbfXSKg4sd44Pbsa4j1y/heW7YRSwU1qj5U9AZZfzPVAVXWjblHQQTntWspUGuWVgTODa29XvQQFjLQr+1/RcCh0=
