language: ruby

sudo: false

cache: bundler

deploy:
  provider: script
  script: scripts/post-advisories.sh
  on:
    branch: master

notifications:
  irc: chat.freenode.net#rubysec

env:
  global:
    - secure: "ceZr5Z6QHDIzVQP7oS6lY/ffH4e1Va+zJcmYZ4IS2Nk2O926lE6YGnpqFCiMGxeYZUw2mv24yDvErvkVKYcQyOa4h/sXvFyPFJiRZuaa3n3/g81eHHmE0OAdKK2CbMkQkI1+hjoMQkI4BriGw15/lu2+U6ldqoM7o/NbY65Epho="
